// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_cursor
NumericVector get_cursor();
RcppExport SEXP _KeyboardSimulator_get_cursor() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_cursor());
    return rcpp_result_gen;
END_RCPP
}
// mouse_left_click
void mouse_left_click();
RcppExport SEXP _KeyboardSimulator_mouse_left_click() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    mouse_left_click();
    return R_NilValue;
END_RCPP
}
// mouse_left_hold
void mouse_left_hold();
RcppExport SEXP _KeyboardSimulator_mouse_left_hold() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    mouse_left_hold();
    return R_NilValue;
END_RCPP
}
// mouse_left_release
void mouse_left_release();
RcppExport SEXP _KeyboardSimulator_mouse_left_release() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    mouse_left_release();
    return R_NilValue;
END_RCPP
}
// mouse_middle_click
void mouse_middle_click();
RcppExport SEXP _KeyboardSimulator_mouse_middle_click() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    mouse_middle_click();
    return R_NilValue;
END_RCPP
}
// mouse_middle_hold
void mouse_middle_hold();
RcppExport SEXP _KeyboardSimulator_mouse_middle_hold() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    mouse_middle_hold();
    return R_NilValue;
END_RCPP
}
// mouse_middle_release
void mouse_middle_release();
RcppExport SEXP _KeyboardSimulator_mouse_middle_release() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    mouse_middle_release();
    return R_NilValue;
END_RCPP
}
// mouse_right_click
void mouse_right_click();
RcppExport SEXP _KeyboardSimulator_mouse_right_click() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    mouse_right_click();
    return R_NilValue;
END_RCPP
}
// mouse_right_hold
void mouse_right_hold();
RcppExport SEXP _KeyboardSimulator_mouse_right_hold() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    mouse_right_hold();
    return R_NilValue;
END_RCPP
}
// mouse_right_release
void mouse_right_release();
RcppExport SEXP _KeyboardSimulator_mouse_right_release() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    mouse_right_release();
    return R_NilValue;
END_RCPP
}
// MouseMove
void MouseMove(int x, int y);
RcppExport SEXP _KeyboardSimulator_MouseMove(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    MouseMove(x, y);
    return R_NilValue;
END_RCPP
}
// MouseMove_loop
void MouseMove_loop(NumericVector xaxis_path, NumericVector yaxis_path, double time_Seg);
RcppExport SEXP _KeyboardSimulator_MouseMove_loop(SEXP xaxis_pathSEXP, SEXP yaxis_pathSEXP, SEXP time_SegSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xaxis_path(xaxis_pathSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yaxis_path(yaxis_pathSEXP);
    Rcpp::traits::input_parameter< double >::type time_Seg(time_SegSEXP);
    MouseMove_loop(xaxis_path, yaxis_path, time_Seg);
    return R_NilValue;
END_RCPP
}
// press_c
void press_c(Rcpp::NumericVector x, Rcpp::NumericVector s, Rcpp::LogicalVector p);
RcppExport SEXP _KeyboardSimulator_press_c(SEXP xSEXP, SEXP sSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type p(pSEXP);
    press_c(x, s, p);
    return R_NilValue;
END_RCPP
}
// press_and_release_c
void press_and_release_c(Rcpp::NumericVector x, Rcpp::NumericVector s, Rcpp::LogicalVector p);
RcppExport SEXP _KeyboardSimulator_press_and_release_c(SEXP xSEXP, SEXP sSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type p(pSEXP);
    press_and_release_c(x, s, p);
    return R_NilValue;
END_RCPP
}
// release_c
void release_c(Rcpp::NumericVector x, Rcpp::NumericVector s, Rcpp::LogicalVector p);
RcppExport SEXP _KeyboardSimulator_release_c(SEXP xSEXP, SEXP sSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type p(pSEXP);
    release_c(x, s, p);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_KeyboardSimulator_get_cursor", (DL_FUNC) &_KeyboardSimulator_get_cursor, 0},
    {"_KeyboardSimulator_mouse_left_click", (DL_FUNC) &_KeyboardSimulator_mouse_left_click, 0},
    {"_KeyboardSimulator_mouse_left_hold", (DL_FUNC) &_KeyboardSimulator_mouse_left_hold, 0},
    {"_KeyboardSimulator_mouse_left_release", (DL_FUNC) &_KeyboardSimulator_mouse_left_release, 0},
    {"_KeyboardSimulator_mouse_middle_click", (DL_FUNC) &_KeyboardSimulator_mouse_middle_click, 0},
    {"_KeyboardSimulator_mouse_middle_hold", (DL_FUNC) &_KeyboardSimulator_mouse_middle_hold, 0},
    {"_KeyboardSimulator_mouse_middle_release", (DL_FUNC) &_KeyboardSimulator_mouse_middle_release, 0},
    {"_KeyboardSimulator_mouse_right_click", (DL_FUNC) &_KeyboardSimulator_mouse_right_click, 0},
    {"_KeyboardSimulator_mouse_right_hold", (DL_FUNC) &_KeyboardSimulator_mouse_right_hold, 0},
    {"_KeyboardSimulator_mouse_right_release", (DL_FUNC) &_KeyboardSimulator_mouse_right_release, 0},
    {"_KeyboardSimulator_MouseMove", (DL_FUNC) &_KeyboardSimulator_MouseMove, 2},
    {"_KeyboardSimulator_MouseMove_loop", (DL_FUNC) &_KeyboardSimulator_MouseMove_loop, 3},
    {"_KeyboardSimulator_press_c", (DL_FUNC) &_KeyboardSimulator_press_c, 3},
    {"_KeyboardSimulator_press_and_release_c", (DL_FUNC) &_KeyboardSimulator_press_and_release_c, 3},
    {"_KeyboardSimulator_release_c", (DL_FUNC) &_KeyboardSimulator_release_c, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_KeyboardSimulator(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
