# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mouse_left_click <- function() {
    invisible(.Call('_KeyboardSimulator_mouse_left_click', PACKAGE = 'KeyboardSimulator'))
}

mouse_left_hold <- function() {
    invisible(.Call('_KeyboardSimulator_mouse_left_hold', PACKAGE = 'KeyboardSimulator'))
}

mouse_left_release <- function() {
    invisible(.Call('_KeyboardSimulator_mouse_left_release', PACKAGE = 'KeyboardSimulator'))
}

mouse_right_click <- function() {
    invisible(.Call('_KeyboardSimulator_mouse_right_click', PACKAGE = 'KeyboardSimulator'))
}

mouse_right_hold <- function() {
    invisible(.Call('_KeyboardSimulator_mouse_right_hold', PACKAGE = 'KeyboardSimulator'))
}

mouse_right_release <- function() {
    invisible(.Call('_KeyboardSimulator_mouse_right_release', PACKAGE = 'KeyboardSimulator'))
}

press_c <- function(x) {
    invisible(.Call('_KeyboardSimulator_press_c', PACKAGE = 'KeyboardSimulator', x))
}

press_and_release_c <- function(x) {
    invisible(.Call('_KeyboardSimulator_press_and_release_c', PACKAGE = 'KeyboardSimulator', x))
}

release_c <- function(x) {
    invisible(.Call('_KeyboardSimulator_release_c', PACKAGE = 'KeyboardSimulator', x))
}

